### ISSUE TITLE
Failed to reslove firebase messaging dependency version 5.16.0

### ISSUE THREAD

**Issue by mhrjnamar** [MobiDevelop/robovm-robopods#103]
I am getting following error while trying to integrate firebase messaging 
![Screen Shot 2020-08-15 at 18 20 02](https://user-images.githubusercontent.com/17248241/90312662-ec550400-df25-11ea-8209-733f6da121b7.png)

**Comment by itsabhiaryan** [comment]
@mhrjnamar 
5.16.0 version of robopods under mobidevelop group not released yet. Use 2.2.3 or  2.2.4-SNAPSHOT version of robopods.
