### ISSUE TITLE
Does not compile with latest SDK on the README.md

### ISSUE THREAD

**Issue by allanstevens** [MobiDevelop/robovm-robopods#109]
Does not compile with latest SDK on the README.md.  Since version 8 it looks like there has been some breaking api changes.

Will need to use the latest version 7 api at dl.google.com/dl/cpdc/7adc882ba6ea0623/Google-Mobile-Ads-SDK-7.69.0.tar.gz (took a while to track the link down).

Is there any chance there will be an update to support version 8+ ?

**Comment by obigu** [comment]
Duplicate https://github.com/MobiVM/robovm-robopods/issues/100
