### ISSUE TITLE
Unable to use facebook robopod

### ISSUE THREAD

**Issue by kali-gandaki** [MobiDevelop/robovm-robopods#21]
Hello , 
I am unable to use facebook . I am using the latest version of robopod and robovm . I get the following error during compilation 

[ERROR] ld: framework not found Bolts
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't compile app

Libgdx Version 1.9.5
robovm version 2.3.0
robopod version 2.2.1-SNAPSHOT

**Comment by Tom-Ski** [comment]
Add the bolts framework, the robopods aren't fat jars.
