### ISSUE TITLE
Where can I find .framework files for Fabric bindings?

### ISSUE THREAD

**Issue by ghost** [MobiDevelop/robovm-robopods#24]
I can't find Fabric 1.6.8 and crashlytics 3.7.3 on Fabric's site. Where can I get it?

![image](https://cloud.githubusercontent.com/assets/5736157/23330698/9aaade88-fb65-11e6-880c-ea650ee553a8.png)

**Comment by alex-dorokhov** [comment]
If there are no frameworks on an official website, then you can try to find them on https://cocoapods.org . Once you found the framework. Search for its Podspec file. In the pod spec you can find path to framework files and download them. It's not so convenient, but we have to live with it for now.

**In case you are complaining about versions mismatch.**
The versions which are listed on the screenshot you provided are the versions which were used to create the bindings. Usually the API is not changed so fast, so you can you existing bindings with newer versions of frameworks.

**Comment by keesvandieren** [comment]
I have integrated current version of Fabric. Downloaded frameworks from https://fabric.io/kits/ios/crashlytics/manual-install 

Also created https://github.com/MobiVM/robovm-robopods/pull/46 with instructions for adding Crashlytics
