### ISSUE TITLE
linker command failed with exit code 1 using Facebook, Google ads and possibly others.

### ISSUE THREAD

**Issue by WillCalderwood** [MobiDevelop/robovm-robopods#25]
I spent a day struggling with this trying to work out what's going on with this on my game - and failed. So I decided to start from scratch with a freshly created libgdx project to see if I could recreate the issue.

I created a new project using the setup program and ran it on an iOS device and all worked as expected. I then added the dependency.

        compile 'com.mobidevelop.robovm:robopods-facebook-ios:2.2.1'

and reran. This produced the following error. (I also tried with the google ads binding with the same issue.)

```
21:03:42: Executing external task 'launchIOSDevice'...
Configuration on demand is an incubating feature.
:core:compileJava UP-TO-DATE
:core:processResources UP-TO-DATE
:core:classes UP-TO-DATE
:core:jar UP-TO-DATE
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
:ios:compileJava
:ios:processResources UP-TO-DATE
:ios:classes
:ios:jar UP-TO-DATE
:ios:assemble UP-TO-DATE
:ios:compileTestJava UP-TO-DATE
:ios:processTestResources UP-TO-DATE
:ios:testClasses UP-TO-DATE
:ios:test UP-TO-DATE
:ios:check UP-TO-DATE
:ios:build UP-TO-DATE
:ios:launchIOSDevice
Classpath entry /Users/WillCalderwood/Downloads/test/ios/build/resources/main does not exist
ld: framework not found FBSDKCoreKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)
:ios:launchIOSDevice FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ios:launchIOSDevice'.
> Failed to launch IOS Device

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 14.646 secs
Command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -o /Users/WillCalderwood/Downloads/test/ios/build/robovm.tmp/IOSLauncher -arch armv7 -Wl,-filelist,/Users/WillCalderwood/Downloads/test/ios/build/robovm.tmp/objects0 -L /Users/WillCalderwood/.m2/repository/com/mobidevelop/robovm/robovm-dist/2.3.0/unpacked/robovm-2.3.0/lib/vm/ios/thumbv7 -ObjC -exported_symbols_list /Users/WillCalderwood/Downloads/test/ios/build/robovm.tmp/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -fPIC -miphoneos-version-min=7.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk -lrobovm-bc -force_load /Users/WillCalderwood/.m2/repository/com/mobidevelop/robovm/robovm-dist/2.3.0/unpacked/robovm-2.3.0/lib/vm/ios/thumbv7/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -lz -liconv -lsqlite3 -framework Foundation -framework FBSDKCoreKit -framework Bolts -framework AVFoundation -framework CoreGraphics -framework CoreMedia -framework CoreMotion -framework StoreKit -framework FBSDKLoginKit -framework FBSDKMessengerShareKit -framework FBNotifications -framework ImageIO -framework UIKit -framework FBSDKShareKit -framework OpenGLES -framework QuartzCore -framework OpenAL -framework AudioToolbox -force_load /Users/WillCalderwood/.robovm/cache/ios/thumbv7/release/Users/WillCalderwood/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.5/80fed8c3dbf915df8e93c0ed8943e2e5e569e513/gdx-platform-1.9.5-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libgdx.a -force_load /Users/WillCalderwood/.robovm/cache/ios/thumbv7/release/Users/WillCalderwood/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-platform/1.9.5/80fed8c3dbf915df8e93c0ed8943e2e5e569e513/gdx-platform-1.9.5-natives-ios.jar.extracted/META-INF/robovm/ios/libs/libObjectAL.a -lz -framework MobileCoreServices -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks' failed (Exit value: 1)
21:03:57: External task execution finished 'launchIOSDevice'.

```

This was just a bog standard libgdx setup with no changes, running Xcode 8.2.1.

I'm amazed no one else is reporting this error, so I'm wondering if I'm doing something really stupid here? But I can't see what I might have messed up with a new project and just adding a single dependency.

**Comment by Tom-Ski** [comment]
`ld: framework not found FBSDKCoreKit`

Means the framework that is trying to be linked is not existent, so you need to add it yourself to the libs folder, reference it in the robovm.xml.  The dependencies are not fat jars, so all the required frameworks arent bundled in the jars.

**Comment by WillCalderwood** [comment]
@Tom-Ski Thanks for that - I'm not that clued up on the iOS side of things. The bit in the robopods documentation that says:

> Just add a depencency to your Maven or Gradle build files and you are ready to go!

Made need some clarification!

**Comment by WillCalderwood** [comment]
@Tom-Ski Thanks for that - that sorted it.

Do you mind if I ask one more [semi-related] question?

I have an ios-core module that I share between games. If I try adding the Framework to that then I'm just getting the error above. Is this possible, or do I need to add the Framework to the module for the game itself? If there are multiple robovm.xml files across modules are they merged?

If I update the robovm.xml and include the Framework in the game module, I'm still able to reference it from within the ios-core module, so I can easily work around this, it's just not the structure I'd envisaged.

Thanks

I'll update some documentation to help out other stumbling across this.

**Comment by Tom-Ski** [comment]
Sorry @WillCalderwood I missed this message.

The robovm.xml should get merged yes, but if you have added the frameworks to a libs folder in your ios-core project, other projects wont automatically inherit those from a base project unless you tell them to. 

You should be able to do this with a build system easily enough.
