### ISSUE TITLE
No Pause or Resume Call after Admob Interstitial

### ISSUE THREAD

**Issue by mustii82** [MobiDevelop/robovm-robopods#27]
Normally a Interstitial should call the Pause Method and after finishing the Interstitial Libgdx normally call the Resume Method like in Android.

But the actual Binding don't do that.

**Comment by Tom-Ski** [comment]
That is only the case with android. The iOS SDK for admob differs in that it doesnt background your app to display interstitials. If you want to mimic this behaviour, you can override the delegate for the interstitial and pause/resume your game then.

WillPresentScreen add WillDismissScreen are the methods you'll want to hook into.
