### ISSUE TITLE
Google Admob Banner on Bottom doesn't work

### ISSUE THREAD

**Issue by mustii82** [MobiDevelop/robovm-robopods#28]
I want to set my Banner to the Bottom of the Screen but it doesn't work.

I tried: adview.setFrame(new CGRect(100,100,100,100)); and adview.setCenter(100,100)

But the X and Y Position is always 0,0

**Comment by nnkdev** [comment]
Hi mustii82,
Can you guide me how to use robopods to show admob banner?
I follow this tutorial: https://github.com/libgdx/libgdx/wiki/Admob-in-libgdx#ios-setup-robovm
 it's ok but libadmob.a has not been updated.
So I want to use Google Mobile Ads to update the latest ones.

**Comment by mustii82** [comment]
I get it work with set centerX and setCenterY  setX and setY didnt work for me I think its a binding problem.

**Comment by nnkdev** [comment]
Fortunately, it worked.

You use SmartBannerPortrait() , then you can set position banner Top or Bottom.

**Comment by nnkdev** [comment]
Hi mustii82,
Can you use Game Center in your game? I don't see it update here.

**Comment by mustii82** [comment]
I didnt try it but im sure it is problematic. Since Robovms closing its very difficult to get iOS bindings work. We even haven't a working iOS In app purchase sample.

**Comment by Tom-Ski** [comment]
If you provide a self contained test that demonstrates your issue we can look into it, unfortunately without that you are not likely to receive any assistance.

**Comment by hoangtunho2611** [comment]
Hi Tom-Ski,
Can you tell me. Does AdMob reward video ads work? I did not find anything to say about it. If it works, you can give me little guidance.
Good day,

**Comment by obigu** [comment]
I use AdMob banner at the bottom as well as Game Center with no issues. Have you sorted your problem, what is the issue exactly?

**Comment by mustii82** [comment]
After the new mobivm pods update it worked
