### ISSUE TITLE
Fabric not working with latest version

### ISSUE THREAD

**Issue by NathanMBui** [MobiDevelop/robovm-robopods#30]
I installed the lasted version of Fabric (3.8.4) and my app start with this error:
java.lang.UnsatisfiedLinkError: Failed to resolve native function 'CLSLog' for method public static native void org.robovm.pods.fabric.crashlytics.Crashlytics.log(java.lang.String,org.robovm.apple.foundation.NSObject,org.robovm.apple.foundation.NSObject,org.robovm.apple.foundation.NSObject,org.robovm.apple.foundation.NSObject,org.robovm.apple.foundation.NSObject) with @Bridge annotation @org.robovm.rt.bro.annotation.Bridge(symbol=CLSLog, dynamic=false, optional=false) in library @org.robovm.rt.bro.annotation.Library(value=__internal__)
	at org.robovm.rt.bro.Runtime.resolveBridge(Runtime.java)
	at org.robovm.rt.bro.Bro.bind(Bro.java)
	at org.robovm.objc.ObjCRuntime.bind(ObjCRuntime.java)
	at org.robovm.pods.fabric.crashlytics.Crashlytics.<clinit>(Crashlytics.java)
	at com.clbbandao.game.ios.IOSLauncher.didFinishLaunching(IOSLauncher.java)
	at com.badlogic.gdx.backends.iosrobovm.IOSApplication$Delegate.$cb$application$didFinishLaunchingWithOptions$(IOSApplication.java)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java)
	at com.clbbandao.game.ios.IOSLauncher.main(IOSLauncher.java)

**Comment by fechy** [comment]
@NathanMBui: FYI, I've checked out the Robopods project, linked Crashlytics directly to my own project from gradle, and commenting out all the "log" methods, compiled, and all works now :)

Not the greatest of the solutions but I was able to use it, at least until its really fixed

**Comment by NathanMBui** [comment]
@fechy Thanks for your information. It did work but when a make a force crash, fabric didn't receive any report. Have you face this issue or I have just missed something:
```
public boolean didFinishLaunching(UIApplication application, UIApplicationLaunchOptions launchOptions) {
        boolean finished = super.didFinishLaunching(application, launchOptions);

        Crashlytics.getSharedInstance();
        Crashlytics.start(crashlyticApiKey);

        return finished;
    }
```

**Comment by fechy** [comment]
@NathanMBui I dont initialise it like that though, thats the old way. The recomended new way is:
````java
public boolean didFinishLaunching(UIApplication application, UIApplicationLaunchOptions launchOptions) {
    boolean finished = super.didFinishLaunching(application, launchOptions);

    Fabric.with(Crashlytics.class);

    return finished;
}
````

And the credentials you add them on the Info.plist.xml:
````xml
<key>Fabric</key>
    <dict>
        <key>APIKey</key>
        <string>your-secret-key</string>
        <key>Kits</key>
        <array>
            <dict>
                <key>KitInfo</key>
                <dict/>
                <key>KitName</key>
                <string>Crashlytics</string>
            </dict>
        </array>
    </dict>
````

This way it worked for me, however I had to comment out those lines I've mentioned.

**Comment by NathanMBui** [comment]
It works, thank you very much @fechy,
Hope they'll fix those "log" methods soon

**Comment by obigu** [comment]
@fechy Probably not the best place to ask but I'm very interested on this, do you see symbolicated crash reports using Crashlytics? Several posts on different forums say RoboVM doesn't work with Crashlytics so I'm curious to know about your experience.

**Comment by fechy** [comment]
@NathanMBui with some more digging I realise the problem was way simpler, no need for commenting out those CLS logs. And the solution is in the repo itself 🥇 , you just need to add this lines to your *robovm.xml*:
```xml
<exportedSymbols>
      <symbol>CLS*</symbol>
</exportedSymbols>
```

@obigu I do. For that you will have to upload the dSYM file directly to Fabric (Search missing_dsyms on Fabric's docs). I use Fastlane (https://fastlane.tools) for building the IPAs and upload them to Beta. Makes things easier.

**Comment by NathanMBui** [comment]
@fechy Thank for your information. Actually they just added it in the ReadMe 3 months ago (after I opened this issue).
So it should be closed now.
Thank you for all your helps

**Comment by nnkdev** [comment]
Hi @NathanMBui , @fechy 
"exportedSymbols should be in RoboPod robovm.xml, not in app robovm.xml"
Where is the RoboPod robovm.xml file?

In build.gradle, i add compile:
compile "com.mobidevelop.robovm:robopods-fabric-ios:2.2.1"
compile "com.mobidevelop.robovm:robopods-fabric-ios-crashlytics:2.2.1"
Is it correct?

**Comment by NathanMBui** [comment]
@hoangtunho2611 
where did you get that quote?. Just add those lines into your project robovm.xml and it should work
And yes, it is correct.

PS: read README file for more details

**Comment by nnkdev** [comment]
@NathanMBui 
I get quote here: https://github.com/MobiVM/robovm-robopods/tree/master/fabric/ios-crashlytics

I add those lines into my project robovm.xml and build on Simulator.

I received this error.
[ERROR] ld: framework not found Crashlytics
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] Couldn't compile app

**Comment by NathanMBui** [comment]
I think you get it wrong. It is a commit's comment. Just add those lines into your project robovm to make sure your app can run then remove it later to see if it works too. The problem might be that you missing .framework files.
Please read "getting started" here: [https://github.com/MobiVM/robovm-robopods/tree/master/fabric](url)

**Comment by nnkdev** [comment]
@NathanMBui 
I copy 2 file .framework (Fabric.framework and Crashlytics.framework) from xCode to ios/libs my project.
I have built on the simulator and no errors.
Thanks,

**Comment by nnkdev** [comment]
@NathanMBui 
I have 3 issues not yet understood, please explain to me.
1. Have Fabric crashlytics work on simulator report crash to Fabric.io dashboard?

And guide here: https://github.com/MobiVM/robovm-robopods/tree/master/fabric/ios-crashlytics
2. You need to configure Robovm to report uncaught exceptions as crashes. Call org.robovm.apple.foundation.NSException#registerDefaultJavaUncaughtExceptionHandler in com.badlogic.gdx.backends.iosrobovm.IOSApplication.Delegate#didFinishLaunching.
how to use it?

3. Additionally you can add this line to enable debug:
Crashlytics.getSharedInstance().setDebugMode(true);
Where is call this command?

Thanks again !

**Comment by NathanMBui** [comment]
@hoangtunho2611 
1. I think it should work on simulator and it takes time to report to dashboard.
2. call this inside didFinishLaunching:
`NSException.registerDefaultJavaUncaughtExceptionHandler();`
3. Call it anywhere after you init fabric with 
`Fabric.with(Crashlytics.class);`

And you should create another issue instead of commenting on this one
