### ISSUE TITLE
How to use Game Center in ios project?

### ISSUE THREAD

**Issue by nnkdev** [MobiDevelop/robovm-robopods#31]
How to use Game Center in ios project?
I play some games on iphone 5s (ios 10.3.1) from the App Store, I still see the leaderboard score from Game Center.
BlueRiverInteractive /robovm-ios-bindings/gamecenter   is Deprecated.

Thanks,

**Comment by Tom-Ski** [comment]
Use the bindings in robovm core itself.

**Comment by nnkdev** [comment]
@Tom-Ski ,
I worry when it bother you. I have published my game on App store. Game Center on ios 9 works well, but with ios 10 it does not work. Please help me !

This my game: https://itunes.apple.com/app/coby-shy/id1255778488

**Comment by Tom-Ski** [comment]
As far as I know there isn't an issue as long as you are using the latest robovm, can you post an issue to MobiVM/robovm repository with the code you are using with relevant details such as versions you are using?

**Comment by nnkdev** [comment]
Thank @Tom-Ski  for answering me, i will create a new issue with the code i use.
