### ISSUE TITLE
Maven not installing Chartboost correctly

### ISSUE THREAD

**Issue by jrdzha** [MobiDevelop/robovm-robopods#4]
I'm trying to get Chartboost via maven with the following commands:

git clone https://github.com/MobiDevelop/robovm-robopods
cd robovm-robopods
mvn -N install
mvn install

But the only libraries that get installed are:
robopods-google-apis-ios        robopods-google-mobile-ads-ios      robopods-parent
robopods-google-apis-parent     robopods-google-mobile-ads-parent

I'm guessing theres something missing in the pom file?

**Comment by Tom-Ski** [comment]
Builds OK for me, make sure you have the latest commits in your repository.  Note they are here https://oss.sonatype.org/content/repositories/snapshots/com/mobidevelop/robovm/ also if you wanted to test them.

Otherwise, pastebin your full log from the mvn install.

**Comment by jrdzha** [comment]
Ok so for gradle dependencies we need
        compile "com.mobidevelop.robovm:robopods-chartboost-ios:2.2.0-SNAPSHOT"
not
        compile "org.robovm:robopods-chartboost-ios:$robopodsVersion"

I can now build the project, but I still cannot import the library...

**Comment by jrdzha** [comment]
Do I need to download anything from https://oss.sonatype.org/content/repositories/snapshots/com/mobidevelop/robovm/

I thought that all I had to do was include
compile "com.mobidevelop.robovm:robopods-chartboost-ios:2.2.0-SNAPSHOT"

in my build.gradle...

**Comment by Tom-Ski** [comment]
You need the repository, which is "https://oss.sonatype.org/content/repositories/snapshots/", if you used the libgdx project generator you should already have this in allprojects { repositories {} }

If that is all good, you can just refresh gradle in your IDE. If you are using eclipse you may need to run the cleanEclipse gradle task from command line, or simply just re-import your project.  With IDEA/AS you can just sync gradle.

If you're having trouble with that, pastebin your build.gradle

**Comment by jrdzha** [comment]
Yeah I did all of that but I still can't do import the chartboost library :/

**Comment by Tom-Ski** [comment]
What IDE? Perhaps pop into the gitter https://gitter.im/MobiDevelop/robovm

**Comment by jrdzha** [comment]
Ok I'm going on right now
I'm usting intellij

**Comment by jrdzha** [comment]
Configuration on demand is an incubating feature.
:ios:dependencies

---

## Project :ios

archives - Configuration for archive artifacts.
No dependencies

compile - Compile classpath for source set 'main'.
+--- project :core
|    +--- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-box2d:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-controllers:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-ai:1.8.0
|    |    --- com.badlogicgames.gdx:gdx:1.9.1 -> 1.9.3
|    +--- com.badlogicgames.ashley:ashley:1.7.0
|    |    --- com.badlogicgames.gdx:gdx:1.7.1 -> 1.9.3
|    +--- com.badlogicgames.gdx:gdx-freetype:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    --- com.badlogicgames.box2dlights:box2dlights:1.4
|         --- com.badlogicgames.gdx:gdx-box2d:1.6.2 -> 1.9.3 (_)
+--- com.mobidevelop.robovm:robovm-rt:2.2.0-SNAPSHOT
+--- com.mobidevelop.robovm:robovm-cocoatouch:2.2.0-SNAPSHOT
|    --- com.mobidevelop.robovm:robovm-objc:2.2.0-SNAPSHOT
+--- com.badlogicgames.gdx:gdx-backend-robovm:1.9.3
|    +--- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.mobidevelop.robovm:robovm-cocoatouch:2.1.0 -> 2.2.0-SNAPSHOT (_)
|    +--- com.mobidevelop.robovm:robovm-objc:2.1.0 -> 2.2.0-SNAPSHOT
|    --- com.mobidevelop.robovm:robovm-rt:2.1.0 -> 2.2.0-SNAPSHOT
+--- com.badlogicgames.gdx:gdx-platform:1.9.3
+--- com.badlogicgames.gdx:gdx-box2d-platform:1.9.3
+--- com.badlogicgames.gdx:gdx-freetype-platform:1.9.3
--- com.mobidevelop.robovm:robopods-chartboost-ios:2.2.0-SNAPSHOT
     +--- com.mobidevelop.robovm:robovm-rt:2.2.0-SNAPSHOT
     +--- com.mobidevelop.robovm:robovm-objc:2.2.0-SNAPSHOT
     --- com.mobidevelop.robovm:robovm-cocoatouch:2.2.0-SNAPSHOT (*)

default - Configuration for default artifacts.
+--- project :core
|    +--- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-box2d:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-controllers:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-ai:1.8.0
|    |    --- com.badlogicgames.gdx:gdx:1.9.1 -> 1.9.3
|    +--- com.badlogicgames.ashley:ashley:1.7.0
|    |    --- com.badlogicgames.gdx:gdx:1.7.1 -> 1.9.3
|    +--- com.badlogicgames.gdx:gdx-freetype:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    --- com.badlogicgames.box2dlights:box2dlights:1.4
|         --- com.badlogicgames.gdx:gdx-box2d:1.6.2 -> 1.9.3 (_)
+--- com.mobidevelop.robovm:robovm-rt:2.2.0-SNAPSHOT
+--- com.mobidevelop.robovm:robovm-cocoatouch:2.2.0-SNAPSHOT
|    --- com.mobidevelop.robovm:robovm-objc:2.2.0-SNAPSHOT
+--- com.badlogicgames.gdx:gdx-backend-robovm:1.9.3
|    +--- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.mobidevelop.robovm:robovm-cocoatouch:2.1.0 -> 2.2.0-SNAPSHOT (_)
|    +--- com.mobidevelop.robovm:robovm-objc:2.1.0 -> 2.2.0-SNAPSHOT
|    --- com.mobidevelop.robovm:robovm-rt:2.1.0 -> 2.2.0-SNAPSHOT
+--- com.badlogicgames.gdx:gdx-platform:1.9.3
+--- com.badlogicgames.gdx:gdx-box2d-platform:1.9.3
+--- com.badlogicgames.gdx:gdx-freetype-platform:1.9.3
--- com.mobidevelop.robovm:robopods-chartboost-ios:2.2.0-SNAPSHOT
     +--- com.mobidevelop.robovm:robovm-rt:2.2.0-SNAPSHOT
     +--- com.mobidevelop.robovm:robovm-objc:2.2.0-SNAPSHOT
     --- com.mobidevelop.robovm:robovm-cocoatouch:2.2.0-SNAPSHOT (*)

runtime - Runtime classpath for source set 'main'.
+--- project :core
|    +--- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-box2d:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-controllers:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-ai:1.8.0
|    |    --- com.badlogicgames.gdx:gdx:1.9.1 -> 1.9.3
|    +--- com.badlogicgames.ashley:ashley:1.7.0
|    |    --- com.badlogicgames.gdx:gdx:1.7.1 -> 1.9.3
|    +--- com.badlogicgames.gdx:gdx-freetype:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    --- com.badlogicgames.box2dlights:box2dlights:1.4
|         --- com.badlogicgames.gdx:gdx-box2d:1.6.2 -> 1.9.3 (_)
+--- com.mobidevelop.robovm:robovm-rt:2.2.0-SNAPSHOT
+--- com.mobidevelop.robovm:robovm-cocoatouch:2.2.0-SNAPSHOT
|    --- com.mobidevelop.robovm:robovm-objc:2.2.0-SNAPSHOT
+--- com.badlogicgames.gdx:gdx-backend-robovm:1.9.3
|    +--- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.mobidevelop.robovm:robovm-cocoatouch:2.1.0 -> 2.2.0-SNAPSHOT (_)
|    +--- com.mobidevelop.robovm:robovm-objc:2.1.0 -> 2.2.0-SNAPSHOT
|    --- com.mobidevelop.robovm:robovm-rt:2.1.0 -> 2.2.0-SNAPSHOT
+--- com.badlogicgames.gdx:gdx-platform:1.9.3
+--- com.badlogicgames.gdx:gdx-box2d-platform:1.9.3
+--- com.badlogicgames.gdx:gdx-freetype-platform:1.9.3
--- com.mobidevelop.robovm:robopods-chartboost-ios:2.2.0-SNAPSHOT
     +--- com.mobidevelop.robovm:robovm-rt:2.2.0-SNAPSHOT
     +--- com.mobidevelop.robovm:robovm-objc:2.2.0-SNAPSHOT
     --- com.mobidevelop.robovm:robovm-cocoatouch:2.2.0-SNAPSHOT (*)

testCompile - Compile classpath for source set 'test'.
+--- project :core
|    +--- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-box2d:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-controllers:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-ai:1.8.0
|    |    --- com.badlogicgames.gdx:gdx:1.9.1 -> 1.9.3
|    +--- com.badlogicgames.ashley:ashley:1.7.0
|    |    --- com.badlogicgames.gdx:gdx:1.7.1 -> 1.9.3
|    +--- com.badlogicgames.gdx:gdx-freetype:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    --- com.badlogicgames.box2dlights:box2dlights:1.4
|         --- com.badlogicgames.gdx:gdx-box2d:1.6.2 -> 1.9.3 (_)
+--- com.mobidevelop.robovm:robovm-rt:2.2.0-SNAPSHOT
+--- com.mobidevelop.robovm:robovm-cocoatouch:2.2.0-SNAPSHOT
|    --- com.mobidevelop.robovm:robovm-objc:2.2.0-SNAPSHOT
+--- com.badlogicgames.gdx:gdx-backend-robovm:1.9.3
|    +--- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.mobidevelop.robovm:robovm-cocoatouch:2.1.0 -> 2.2.0-SNAPSHOT (_)
|    +--- com.mobidevelop.robovm:robovm-objc:2.1.0 -> 2.2.0-SNAPSHOT
|    --- com.mobidevelop.robovm:robovm-rt:2.1.0 -> 2.2.0-SNAPSHOT
+--- com.badlogicgames.gdx:gdx-platform:1.9.3
+--- com.badlogicgames.gdx:gdx-box2d-platform:1.9.3
+--- com.badlogicgames.gdx:gdx-freetype-platform:1.9.3
--- com.mobidevelop.robovm:robopods-chartboost-ios:2.2.0-SNAPSHOT
     +--- com.mobidevelop.robovm:robovm-rt:2.2.0-SNAPSHOT
     +--- com.mobidevelop.robovm:robovm-objc:2.2.0-SNAPSHOT
     --- com.mobidevelop.robovm:robovm-cocoatouch:2.2.0-SNAPSHOT (*)

testRuntime - Runtime classpath for source set 'test'.
+--- project :core
|    +--- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-box2d:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-controllers:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.badlogicgames.gdx:gdx-ai:1.8.0
|    |    --- com.badlogicgames.gdx:gdx:1.9.1 -> 1.9.3
|    +--- com.badlogicgames.ashley:ashley:1.7.0
|    |    --- com.badlogicgames.gdx:gdx:1.7.1 -> 1.9.3
|    +--- com.badlogicgames.gdx:gdx-freetype:1.9.3
|    |    --- com.badlogicgames.gdx:gdx:1.9.3
|    --- com.badlogicgames.box2dlights:box2dlights:1.4
|         --- com.badlogicgames.gdx:gdx-box2d:1.6.2 -> 1.9.3 (_)
+--- com.mobidevelop.robovm:robovm-rt:2.2.0-SNAPSHOT
+--- com.mobidevelop.robovm:robovm-cocoatouch:2.2.0-SNAPSHOT
|    --- com.mobidevelop.robovm:robovm-objc:2.2.0-SNAPSHOT
+--- com.badlogicgames.gdx:gdx-backend-robovm:1.9.3
|    +--- com.badlogicgames.gdx:gdx:1.9.3
|    +--- com.mobidevelop.robovm:robovm-cocoatouch:2.1.0 -> 2.2.0-SNAPSHOT (_)
|    +--- com.mobidevelop.robovm:robovm-objc:2.1.0 -> 2.2.0-SNAPSHOT
|    --- com.mobidevelop.robovm:robovm-rt:2.1.0 -> 2.2.0-SNAPSHOT
+--- com.badlogicgames.gdx:gdx-platform:1.9.3
+--- com.badlogicgames.gdx:gdx-box2d-platform:1.9.3
+--- com.badlogicgames.gdx:gdx-freetype-platform:1.9.3
--- com.mobidevelop.robovm:robopods-chartboost-ios:2.2.0-SNAPSHOT
     +--- com.mobidevelop.robovm:robovm-rt:2.2.0-SNAPSHOT
     +--- com.mobidevelop.robovm:robovm-objc:2.2.0-SNAPSHOT
     --- com.mobidevelop.robovm:robovm-cocoatouch:2.2.0-SNAPSHOT (*)

(*) - dependencies omitted (listed previously)

BUILD SUCCESSFUL

Total time: 2.842 secs

**Comment by jrdzha** [comment]
ok so the issue for me was I was importing com.mobidevelop._; not importing org.robovm.pods.chartboost._; lol sorry for the stupidity :/
