### ISSUE TITLE
Incomaptible robopods librarries - AppODeal, YandexMetrica, GoogleMobileAds

### ISSUE THREAD

**Issue by balepc** [MobiDevelop/robovm-robopods#50]
Trying to launch iOS game with YandexMetrica, AppoDeal and GoogleMobileAds all together. It doesn't complie.

`duplicate symbol _OBJC_IVAR_$_PodYandexMobileMetrica_FMStatement._query in:
    /ios/libs/YandexMobileMetrica.framework/YandexMobileMetrica(FMDatabase.o)
    /ios/libs/Appodeal.framework/Appodeal(FMDatabase.o)`

I've cleared the cache, but doesn't work.

**Comment by alex-dorokhov** [comment]
Appodeal.framework contains YandexMetrica.framework inside. So to make it work all together you have to remove YandexMetrica.framework from your project's lib folder.
