### ISSUE TITLE
How To Requesting Consent from European Users

### ISSUE THREAD

**Issue by nnkdev** [MobiDevelop/robovm-robopods#56]
https://developers.google.com/admob/ios/eu-consent

I do not understand what I need to do.
Please help me!

**Comment by nnkdev** [comment]
I'm still waiting. I have perfected and used Google's consent form for android games. Please port consent sdk to robopods. 
Thank you very much!

**Comment by obigu** [comment]
You can try to create the bindings yourself and contribute them. It's not hard, you can follow this tutorial that shows how to do it https://dkimitsa.github.io/2017/10/19/bro-gen-tutorial/.

**Comment by varrav** [comment]
Hello!

How to create bindings from [Google Mobile Ads Consent SDK](https://github.com/googleads/googleads-consent-sdk-ios)? Should I convert .xcodeproj to .framework and how?

**Comment by obigu** [comment]
@varrav This is an issue tracker, you can ask for help on the official Gitter channel.

**Comment by varrav** [comment]
@hoangtunho2611 I have implemented Google Consent SDK binding, take a look at:
https://github.com/varrav/robovm-robopods/tree/master/google-consent

Currently tested a bit only on emulator

**Comment by obigu** [comment]
@varrav I think this one could be added to the official repo. Did you get to test it? Want to contribute it as a PR?

**Comment by varrav** [comment]
> @varrav I think this one could be added to the official repo. Did you get to test it? Want to contribute it as a PR?

Good idea! Seems on ios emulators works well. What does it mean 'contribute as a PR'?

**Comment by obigu** [comment]
> > @varrav I think this one could be added to the official repo. Did you get to test it? Want to contribute it as a PR?
> 
> What does it mean 'contribute as a PR'?

If you can submit a Pull Request with the new Consent SDK robopod so that we can review it and merge it easily.

**Comment by varrav** [comment]
> > > @varrav I think this one could be added to the official repo. Did you get to test it? Want to contribute it as a PR?
> > 
> > 
> > What does it mean 'contribute as a PR'?
> 
> If you can submit a Pull Request with the new Consent SDK robopod so that we can review it and merge it easily.

I've never take a part in such development before.. You can assign me an ability to submit PR, but I'm not sure I will use it

**Comment by obigu** [comment]
> > > > @varrav I think this one could be added to the official repo. Did you get to test it? Want to contribute it as a PR?
> > > 
> > > 
> > > What does it mean 'contribute as a PR'?
> > 
> > 
> > If you can submit a Pull Request with the new Consent SDK robopod so that we can review it and merge it easily.
> 
> I've never take a part in such development before.. You can assign me an ability to submit PR, but I'm not sure I will use it

Well, there's always a first time! Anybody can create PRs, it's up to admins to merge them or not. If you want to learn how to contribute to Github repos and how most Open Source Software development works nowadays this is a good opportunity.
