### ISSUE TITLE
Monitor network reachability. Problems in wifi local status

### ISSUE THREAD

**Issue by avazquezdev** [MobiDevelop/robovm-robopods#57]
Hello!
I am making a connectivity monitor for an application I am implementing.
I'm doing some tests to see how it works and I've run into some problems.
The code is simple and I am only monitoring the status of the local wifi and the internet connection.

Code test: https://github.com/avazquezdev/samples-robovm/tree/master/Monitor

1. When I disable wifi (settings), the listener does not receive any notification "unreachable"
2. If I am connected to a Wifi Network and I switch to another Wifi Network, this change is not notified 

Regards!

**Comment by obigu** [comment]
You may try running this sample app https://github.com/robovm/robovm-samples/tree/master/robopods/reachability and check if you also reproduce the issue.

**Comment by obigu** [comment]
Closing this for the moment. Please reopen if you have new info.
