### ISSUE TITLE
Failed to resolve: com.mobidevelop.robovm:robopods-firebase-ios-analytics:2.3.3

### ISSUE THREAD

**Issue by IskanderNazarov** [MobiDevelop/robovm-robopods#61]
I'm trying to add Firebase analytics to my project but there is some error. It's very possible that I'm doing something wrong.

I add this line in my gradle

```
project(":core") {
    apply plugin: "java"


    dependencies {
       .............
        compile "com.mobidevelop.robovm:robopods-firebase-ios-analytics:$robopodsVersion"
   }
}
```

AndroidStudio gives me the next error
`Failed to resolve: com.mobidevelop.robovm:robopods-firebase-ios-analytics:2.3.3`

Sorry if my question is too dumb (

**Comment by obigu** [comment]
Latest stable RoboPods version is 2.2.2. Alternatively you can also use the snapshot version 2.2.3-SNAPSHOT.

**Comment by obigu** [comment]
You may be interested on this PR to use the latest Firebase https://github.com/MobiVM/robovm-robopods/pull/63

**Comment by IskanderNazarov** [comment]
@obigu Thanks, it worked but now it shows another error
```
[ERROR] ld: framework not found FirebaseNanoPB
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Have you any idea how solve this problem?

**Comment by obigu** [comment]
Do you have the old framework dependencies on your robovm.xml (including a dependency to FirebaseNanoPB)? Delete all Firebase framework dependencies from `robovm.xml` as they're already included in the pod.

**Comment by ldthai** [comment]
> @obigu Thanks, it worked but now it shows another error
> 
> ```
> [ERROR] ld: framework not found FirebaseNanoPB
> [ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> Have you any idea how solve this problem?

I got the same problem.
My project have:

compile "com.mobidevelop.robovm:robopods-google-mobile-ads-ios:$robopodsVersion"
compile "com.mobidevelop.robovm:robopods-google-signin-ios:$robopodsVersion"
compile "com.mobidevelop.robovm:robopods-firebase-ios-messaging:$robopodsVersion"

Google mobile ads: 7.31.0
Google Signin: 4.0.0
Firebase Messaging: 5.11.0

Did you solve that?

Thank you!

**Comment by obigu** [comment]
> My project have:
> 
> compile "com.mobidevelop.robovm:robopods-google-mobile-ads-ios:$robopodsVersion"
> compile "com.mobidevelop.robovm:robopods-google-signin-ios:$robopodsVersion"
> compile "com.mobidevelop.robovm:robopods-firebase-ios-messaging:$robopodsVersion"
> 
> Google mobile ads: 7.31.0


What version is $robopodsVersion?

**Comment by ldthai** [comment]
> > My project have:
> > compile "com.mobidevelop.robovm:robopods-google-mobile-ads-ios:$robopodsVersion"
> > compile "com.mobidevelop.robovm:robopods-google-signin-ios:$robopodsVersion"
> > compile "com.mobidevelop.robovm:robopods-firebase-ios-messaging:$robopodsVersion"
> > Google mobile ads: 7.31.0
> 
> What version is $robopodsVersion?

robopodsVersion = "2.2.3-SNAPSHOT"

@obigu  thank you for the reply!

**Comment by obigu** [comment]
@ldthai None of the 3 artifacts you depend on have a dependecy to the `FirebaseNanoPB` framework in their embedded `robovm.xml`. 
If it's not the artifacts I can think ok these possible reasons:
1. You have that framework dependency in your `robovm.xml`
2. You are not using the latest SNAPSHOTS (old versions did depend on `FirebaseNanoPB`).
3. There's another dependency in your `build.gradle` that is not any of those 3 that tries to link the framework

**Comment by obigu** [comment]
Please try the latest version of the bindings for Firebase 5.16.0 (2.2.3-SNASPHOT) which require now to explicitely declare all dependent frameworks on your `robovm.xml`.

Closing this issue, please create a new if you have an issue with the latest bindings.
