### ISSUE TITLE
Undefined symbols for architecture x86_64 when compiling with GoogleMobileAds framework

### ISSUE THREAD

**Issue by codedotspectra** [MobiDevelop/robovm-robopods#68]
#### Issue details
i'm having an error when compiling the app with admob ads

    `Undefined symbols for architecture x86_64:
       "_OBJCCLASS$_WKWebView", referenced from:
           objc-class-ref in GoogleMobileAds(GADOMIDJSExecutorFactory_72b26b7bf73ad99b8affc15d39583171.o)
           objc-class-ref in GoogleMobileAds(GADOMIDAdSessionContext_3a914c7dff81beb3460cff945047d5d7.o)
    ld: symbol(s) not found for architecture x86_64`

Full error : https://pastebin.com/raw/XswaKQv4
Robovm.xml : https://pastebin.com/raw/etddYdD5

GoogleMobileAds framework is installed (in the libs folder)
mobivm ios bindings are installed 

`compile "com.mobidevelop.robovm:robopods-google-mobile-ads-ios:2.2.2"`

i followed this tutorial : https://github.com/MobiVM/robovm-robopods/tree/master/google-mobile-ads/ios#display-ads

**Build Tools:**
- RoboVM Intellij IDEA Plugin v2.3.5
- Gradle (Android studio 3.2.1)
 
**Versions:**
- Robovm: 2.3.3
- XCode: latest
- JDK: latest

**Comment by obigu** [comment]
What version of Google Mobile Ads?
Can you try with AdMob RoboPod version 2.2.3-SNAPSHOT?
Can you also paste your robovm.xml file?

**Comment by codedotspectra** [comment]
i'll try with the snapshot version, i added the robovm file to my question

**Comment by codedotspectra** [comment]
looks like its working, the app finaly launch. does ads work in the emulator ?

**Comment by obigu** [comment]
Yes, ads work in the simulator. Closing the issue now.
