### ISSUE TITLE
Chartboost robopod not compatible with latest chartboost SDK 6.5.1

### ISSUE THREAD

**Issue by gangof-one** [MobiDevelop/robovm-robopods#7]
Unfortunately, the chartboost robopod is not compatible with the latest version of chartboost SDK (6.5.1). 6.5.1 brings compatibility for iOS 10.

Errors when building:

Undefined symbols for architecture armv7:
  "_SecPolicyCreateSSL", referenced from:
      -[Chartboost_AFSecurityPolicy evaluateServerTrust:forDomain:] in Chartboost(AFSecurityPolicy.o)
  "_SecTrustSetPolicies", referenced from:
      -[Chartboost_AFSecurityPolicy evaluateServerTrust:forDomain:] in Chartboost(AFSecurityPolicy.o)
  "_SecCertificateCopyData", referenced from:
      -[Chartboost_AFSecurityPolicy evaluateServerTrust:forDomain:] in Chartboost(AFSecurityPolicy.o)
  "_SecTrustGetCertificateCount", referenced from:
      -[Chartboost_AFSecurityPolicy evaluateServerTrust:forDomain:] in Chartboost(AFSecurityPolicy.o)
  "_SecTrustGetCertificateAtIndex", referenced from:
      -[Chartboost_AFSecurityPolicy evaluateServerTrust:forDomain:] in Chartboost(AFSecurityPolicy.o)
  "_SecCertificateCreateWithData", referenced from:
      -[Chartboost_AFSecurityPolicy setPinnedCertificates:] in Chartboost(AFSecurityPolicy.o)
      -[Chartboost_AFSecurityPolicy evaluateServerTrust:forDomain:] in Chartboost(AFSecurityPolicy.o)
  "_SecPolicyCreateBasicX509", referenced from:
      -[Chartboost_AFSecurityPolicy setPinnedCertificates:] in Chartboost(AFSecurityPolicy.o)
      -[Chartboost_AFSecurityPolicy evaluateServerTrust:forDomain:] in Chartboost(AFSecurityPolicy.o)
  "_SecTrustCreateWithCertificates", referenced from:
      -[Chartboost_AFSecurityPolicy setPinnedCertificates:] in Chartboost(AFSecurityPolicy.o)
      -[Chartboost_AFSecurityPolicy evaluateServerTrust:forDomain:] in Chartboost(AFSecurityPolicy.o)
  "_SecTrustSetAnchorCertificates", referenced from:
      -[Chartboost_AFSecurityPolicy evaluateServerTrust:forDomain:] in Chartboost(AFSecurityPolicy.o)
  "_SecTrustEvaluate", referenced from:
      -[Chartboost_AFSecurityPolicy setPinnedCertificates:] in Chartboost(AFSecurityPolicy.o)
      -[Chartboost_AFSecurityPolicy evaluateServerTrust:forDomain:] in Chartboost(AFSecurityPolicy.o)
      _AFServerTrustIsValid in Chartboost(AFSecurityPolicy.o)
  "_SecTrustCopyPublicKey", referenced from:
      -[Chartboost_AFSecurityPolicy setPinnedCertificates:] in Chartboost(AFSecurityPolicy.o)
      -[Chartboost_AFSecurityPolicy evaluateServerTrust:forDomain:] in Chartboost(AFSecurityPolicy.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
:ios:launchIOSDevice FAILED

**Comment by CoderBaron** [comment]
This is fixed with the new PR #8. Essentially you just need to link the Security framework.
