### ISSUE TITLE
nullPointer when initializing viewcontroller for ads

### ISSUE THREAD

**Issue by codedotspectra** [MobiDevelop/robovm-robopods#70]
hi,
i followed the tutorial to show ads (https://github.com/MobiVM/robovm-robopods/tree/master/google-mobile-ads/ios)

but when i launch the app (emulator), the app crashes and throw a nullPointerException on this :

    viewController = UIApplication.getSharedApplication().getKeyWindow().getRootViewController();

(i'm using Libgdx)
i simply copy pasted this line, is it depreciated/outdated or something ? or maybe i'm missing something

**Comment by obigu** [comment]
Where are you executing this line? You must do it on `didFinishLaunching()` or later.

**Comment by codedotspectra** [comment]
hum.. i still have the error, i may not have the correct synthax for `didFinishLaunching()`

    @Override
    public boolean didFinishLaunching(final UIApplication application, final UIApplicationLaunchOptions launchOptions) {
        initializeAds();
        return true;
    }


    // initialize ads
    private void initializeAds() {
        GADMobileAds.disableSDKCrashReporting();
        if(!adsInitialized) {
            request = new GADRequest();
            request.setTestDevices(Arrays.asList(GADRequest.getSimulatorID()));
            viewController = UIApplication.getSharedApplication().getKeyWindow().getRootViewController();

            GADMobileAds.configure(APP_ID);

            rewardBasedVideoAd = new GADRewardBasedVideoAd();
            rewardBasedVideoAd.setDelegate(new GADRewardBasedVideoAdDelegateAdapter() {
                @Override
                public void didClose(GADRewardBasedVideoAd rewardBasedVideoAd) {
                    rewardBasedVideoAd = createAndLoadVideo();
                    closed = true;
                }
                @Override
                public void didRewardUser(GADRewardBasedVideoAd rewardBasedVideoAd, GADAdReward reward) {
                    rewardBasedVideoAd = createAndLoadVideo();
                    rewarded = true;
                }
            });
            GADRequest request = new GADRequest();
            rewardBasedVideoAd.loadRequest(request, AD_UNIT_ID);

            interstitialAd = new GADInterstitial(AD_UNIT_INTER_ID);
            interstitialAd.setDelegate(new GADInterstitialDelegateAdapter(){
                @Override
                public void didDismissScreen(GADInterstitial ad) {
                    interstitialAd = createAndLoadInterstitial();
                }
            });
            interstitialAd.loadRequest(request);

            adsInitialized = true;
        }
    }

**Comment by obigu** [comment]
You need to call `super.didFinishLaunching(application, launchOptions);` first thing

**Comment by codedotspectra** [comment]
where exactly do i need to call this ? i have to methods, `createApplication()` and `main(String[]argv)`
also i'm not sure what to put in (application, launchOptions) 

here's my `iosLauncher.java` if that can help : https://pastebin.com/9env4iCr

**Comment by obigu** [comment]
Call it as the first line of your `didFinishLaunching()` implementation.

I'm going to close this issue as it's not related to robopods (in libGDX forums you may request for support).
