### ISSUE TITLE
Disable / enable analytics collection

### ISSUE THREAD

**Issue by gerds0n** [MobiDevelop/robovm-robopods#71]
Hi there,

thanks for the bindings! Is there a way to enable analytics collection from code (after initially disabling it in the plist using <key>FIREBASE_ANALYTICS_COLLECTION_ENABLED</key><string>NO</string>)? This is the normal process after consent for data collection is given by your users. The iOS SDK has a method AnalyticsConfiguration.shared().setAnalyticsCollectionEnabled(true) for this... but can't find it in the bindings.

Thank you and greetings,
Gerhard

**Comment by obigu** [comment]
FIRAnalyticsConfiguration is currently not bound. As a workaround until a new version is released in which FIRAnalyticsConfiguration is bound, you can quickly bind it yourself manually creating only the bindings for that class and adding it to your project (if you have troubles you can ask on MobiVM Gitter channel)

**Comment by gerds0n** [comment]
Thank you!
