### ISSUE TITLE
Update Facebook sdk

### ISSUE THREAD

**Issue by SinaZK** [MobiDevelop/robovm-robopods#79]
Hi i integrated the Facebook pod in my game and now in Facebook developer panel i see a warning : Your Facebook SDK is out-of-date. Please upgrade to v5.0 for access to new privacy features.
Please make facebook robopod using Facebook V5.0 sdk.
Thanks.

**Comment by obigu** [comment]
Robopods are updated from time to time thanks to generous contributions of users and are designed to work with the specific version of the SDK listed on their README. 
If you miss a version/binding you can easily create the bindings you need yourself and, even better, contribute them to the community.
