### ISSUE TITLE
Firebase Analytics: Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by thebnich** [MobiDevelop/robovm-robopods#80]
After adding the Firebase Analytics SDK, I see this error when I try to create an IPA (`./gradlew createIPA` in libGDX project):
```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_SKProductsRequest", referenced from:
      objc-class-ref in GoogleAppMeasurement(APMProductsRequest_b4c5e1bd5d891440f37102f602e113af.o)
  "_OBJC_CLASS_$_SKPaymentQueue", referenced from:
      objc-class-ref in GoogleAppMeasurement(APMAnalytics_7a75c1c1ea2dc414eaa5c0403a160869.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm still able to build and run successfully using Android Studio with the RoboVM plugin.

Firebase SDK: 6.3.0
RoboPods: 2.2.3-SNAPSHOT
RoboVM: 2.3.5
robopod.xml: https://pastebin.com/nj2MLYAE

**Comment by thebnich** [comment]
Looks like adding the StoreKit framework fixed the issue. Can this be added to the docs?

**Comment by obigu** [comment]
The current Firebase bindings are for version 5.16.0, probably the StoreKit dependency was added later.

**Comment by thebnich** [comment]
Sure, but the [instructions](https://github.com/MobiVM/robovm-robopods/tree/master/firebase/ios-analytics#install-instructions) link the library from the main Firebase page, which is going to download the latest version. Perhaps the instructions can link directly to the appropriate version at https://dl.google.com/firebase/sdk/ios/5_16_0/Firebase-5.16.0.zip?

Edit: fixed link.
