### ISSUE TITLE
Admob Bindings update

### ISSUE THREAD

**Issue by apelt** [MobiDevelop/robovm-robopods#81]
Hi,
I was trying to use Admob with using Ad content filtering (https://developers.google.com/admob/ios/targeting#Ad_content_filtering) and set the maxAdContentRating parameter regarding the age of the user (which I got from him by using Neutral Age Screen). There is used GADRequestConfiguration class for that. Unfortunately it cannot be resolved. 

Do you plan to update the Admob bindings?

All the best,
Apelt

PS: thank you for your effort and MobiVM project - it really is outstanding!

**Comment by obigu** [comment]
You can try https://github.com/MobiVM/robovm-robopods/pull/77
