### ISSUE TITLE
where can I get the outdated version of the admob lib

### ISSUE THREAD

**Issue by bitdream** [MobiDevelop/robovm-robopods#90]
In the tutorial section it said the version it support is 7.31.0
But in the admob website we can only download the latest version.
Where can we get the version 7.31.0?

**Comment by itsabhiaryan** [comment]
Seems this is not an issue. You can download the required framework from this [link](https://dl.google.com/dl/cpdc/d95f9069274c9b80/Google-Mobile-Ads-SDK-7.31.0.tar.gz), unzip the downloaded file and find your framework inside the extracted folder.
