### ISSUE TITLE
IOSLauncher: How to check build config is Development or Distribution provisioning profile.

### ISSUE THREAD

**Issue by nnkdev** [MobiDevelop/robovm-robopods#91]
I want to get current build config is Development or Distribution provisioning profile. To use ID Ads test for Development environment and my ID Ads for Distribution environment.
With Android platform, it very very easy. With iOS: How to check build config in IOSLauncher?

And, please share for me file Mobile Ads SDK version 7.42.2. I can't download this version because only download latest version.

Thanks you!

**Comment by obigu** [comment]
This is an issue tracker, you can ask for help in the MobiVM Gitter channel https://gitter.im/MobiVM/robovm.
