### ISSUE TITLE
Users report issues with closing interstitial Ads

### ISSUE THREAD

**Issue by UnbackedFan** [MobiDevelop/robovm-robopods#94]
I am having few users report to me that the interstitial ad is not responsive (cannot click the x button to close the ad) or that they get a black screen only. I have tried to reproduce it in simulators and on my iOS devices but I was not able to. I was hoping someone else might have had such issues and could help me resolve it.

Here's some additional information.
- **Device tested on:** iPod touch 7th gen v13.1.3 and iPhone 4 v9.3.5
- **User device where issue occured:** iPhone 6 v12.4.6
- I am using the libGDX framework to develop my app for iOS.

**Comment by obigu** [comment]
You should specify which versions of ad framework(s) and bindings your are using. It happens that some campaigns cause a bug with in ad network SDK (for example some playable ads) and some ad networks SDK versions are also not very stable. If it's just a few users that have reported that is the most probable cause of this issue.

**Comment by UnbackedFan** [comment]
I am using the latest robopods version which is 2.2.3-SNAPSHOT and the Google Mobile Ads framework version 7.52.0 if I'm not mistaken. I wasn't sure how to verify the version from the framework file itself. Does the binding support the latest Google Mobile Ads framework which is 7.58.0?

**Comment by obigu** [comment]
Latest RoboPods version is 2.2.3 (README was outdated). Bindings were created for version 7.42.2. The farther from the version the bindings were created for the more possible changes the API has suffered. Usually, changes in the "minor" (2nd) version number indicate no major changes in the API have occurred. You will probably be able to use 7.58.0 with current bindings except if you need to use recent additions to the API. The kind of issue you describe doesn't seem related to a binding issue.

**Comment by UnbackedFan** [comment]
Alright, I'll try the latest framework version. Thank you for your time.
