### ISSUE TITLE
Fix documentation

### ISSUE THREAD

**Issue by teletubo** [MobiDevelop/robovm-robopods#97]
`@Override
public boolean didFinishLaunching(UIApplication application, UIApplicationLaunchOptions launchOptions) {
    FIRApp.configure()
    return true;
}`

please add call to super.didFinishLaunching otherwise app will crash with 
com.badlogic.gdx.backends.iosrobovm.IOSApplication$Delegate.didBecomeActive

**Comment by obigu** [comment]
Closed via https://github.com/MobiVM/robovm-robopods/commit/24aa36326f4b5d05f51d28c47d1a944becf1a10e
