### ISSUE TITLE
Problem with google-signin-ios (Deprecated API Usage)

### ISSUE THREAD

**Issue by Mory4okVMF** [MobiDevelop/robovm-robopods#98]
IOS don't accept new app. Here is the answer :"ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability."  I think the problem is that you use old version of Google Sign-In SDK for iOS. https://developers.google.com/identity/sign-in/ios/sdk

**Comment by obigu** [comment]
Yeah, the current Google Sign In bindings are for a pretty old version and nobody has contributed to update them for a long time. If you need it and create updated bindings for it, it'd be great if you contributed the change with a PR. If you've never created bindings before you can start with this tutorial: https://dkimitsa.github.io/2017/10/19/bro-gen-tutorial/ and can get help if you get stuck on MobiVM gitter channel (https://gitter.im/MobiVM/robovm).

**Comment by Mory4okVMF** [comment]
Thanks for the quick reply, I’ll do it. I hope for equally fast communication and support in this issue

**Comment by Mory4okVMF** [comment]
Sorry, but for me it was harder than I thought and would take a very long time. But for my project this is really important. This will make you much faster and easier. I am ready to contribute $ 100 so that you have an incentive to do this. It'll be enough?

**Comment by obigu** [comment]
Sorry, I don't do contracts, maybe somebody else is interested, try MobiVM Gitter. I've just had a quick look though and, does Firebase Auth provide the same functionality as standalone Google Sign in? If it does there's an updated pod for it in AltPods repository you can use https://github.com/dkimitsa/robovm-robopods/tree/alt/firebase/.
