### ISSUE TITLE
Outdated firebase/ios-analytics install instructions

### ISSUE THREAD

**Issue by mulkatz** [MobiDevelop/robovm-robopods#99]
The current version of the Google Analytics Framework contains additional libraries that are not described in the README. I thought that the messaging robopod does not need them, so I left them out (compiling was still possible, which confused me).

Here ist the list of frameworks which are needed to use the ios-messaging/ios-analytics robopod:

```
    <framework>FIRAnalyticsConnector</framework>
    <framework>FirebaseAnalytics</framework>
    <framework>FirebaseCore</framework>
    <framework>FirebaseCoreDiagnostics</framework>
    <framework>FirebaseInstallations</framework> <!-- !-->
    <framework>FirebaseMessaging</framework>
    <framework>GoogleAppMeasurement</framework>
    <framework>GoogleDataTransport</framework> <!-- ! -->
    <framework>GoogleDataTransportCCTSupport</framework> <!-- ! -->
    <framework>GoogleUtilities</framework>
    <framework>nanopb</framework>
    <framework>PromisesObjC</framework>
    <framework>Protobuf</framework>
```

Frameworks missing in the repo readme are marked with a line comment

**Comment by obigu** [comment]
Firebase latest pod is for version 5.16.0 and it works with the libraries specified in the README. Remember that each pod and instructions are for a specific SDK version.
